name: Test and Deploy

on:
  push: 
    branches:
      - 'develop'
      - 'test'
      - 'production'
      - 'main'
      
jobs:
  lint:
    secrets: inherit
    uses: ./.github/workflows/job.lint.yml
  smoke-tests:
    secrets: inherit
    uses: ./.github/workflows/job.smoke.yml
  deploy:
    needs: 
      - lint
      - smoke-tests
    secrets: inherit
    uses: ./.github/workflows/job.deploy-gcs.yml
  merge-staging:
    if: github.ref == 'refs/heads/develop'
    needs: 
      - deploy
    secrets: inherit
    uses: ./.github/workflows/job.merge.yml
    with:
      base-branch: 'test'
      target-branch: 'develop'
  merge-production:
    if: github.ref == 'refs/heads/test'
    needs: 
      - merge-staging
    secrets: inherit
    uses: ./.github/workflows/job.merge.yml
    with:
      base-branch: 'main'
      target-branch: 'test'
  release:
    needs: 
      - merge-production
    secrets: inherit
    uses: ./.github/workflows/job.release.yml