name: Test and Deploy

on:
  push: 
    branches:
      - 'develop'
      - 'test'
      - 'production'
      - 'main'
      
jobs:
  lint:
    secrets: inherit
    uses: ./.github/workflows/job.lint.yml
  smoke-tests:
    secrets: inherit
    uses: ./.github/workflows/job.smoke.yml
  deploy:
    needs: 
      - lint
      - smoke-tests
    secrets: inherit
    uses: ./.github/workflows/job.deploy-gcs.yml